/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3st;

/**
 *
 * @author tiago
 */
public class A3Cadstro extends javax.swing.JFrame {

    /**
     * Creates new form A3Cadstro
     */
    public A3Cadstro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeC = new javax.swing.JTextField();
        DataNascimento = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CEP = new javax.swing.JTextField();
        Senha = new javax.swing.JTextField();
        CPF = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Nresidencia = new javax.swing.JTextField();
        Compl = new javax.swing.JTextField();
        ConfirmaS = new javax.swing.JTextField();
        Continuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(937, 667));
        getContentPane().setLayout(null);

        NomeC.setText("Nome Completo");
        NomeC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCActionPerformed(evt);
            }
        });
        getContentPane().add(NomeC);
        NomeC.setBounds(50, 210, 860, 20);

        DataNascimento.setText("Data de Nascimento");
        DataNascimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(DataNascimento);
        DataNascimento.setBounds(50, 260, 320, 20);

        Email.setText("E-mail");
        getContentPane().add(Email);
        Email.setBounds(50, 310, 320, 22);

        jLabel2.setText("Endereço");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 370, 60, 16);

        CEP.setText("CEP");
        CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPActionPerformed(evt);
            }
        });
        getContentPane().add(CEP);
        CEP.setBounds(50, 400, 130, 22);

        Senha.setText("Senha");
        getContentPane().add(Senha);
        Senha.setBounds(50, 490, 300, 22);

        CPF.setText("CPF");
        getContentPane().add(CPF);
        CPF.setBounds(510, 260, 390, 22);

        Tel.setText("Telefone Celular");
        getContentPane().add(Tel);
        Tel.setBounds(510, 310, 390, 22);

        Nresidencia.setText("Numero da Residência");
        getContentPane().add(Nresidencia);
        Nresidencia.setBounds(510, 370, 310, 22);

        Compl.setText("Complemento");
        getContentPane().add(Compl);
        Compl.setBounds(510, 420, 250, 22);

        ConfirmaS.setText("Confirmar Senha");
        getContentPane().add(ConfirmaS);
        ConfirmaS.setBounds(510, 490, 310, 22);

        Continuar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Continuar.setText("Continuar");
        Continuar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(Continuar);
        Continuar.setBounds(380, 570, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\6 CADASTRO.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 665);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCActionPerformed

    private void CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPActionPerformed

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
       A31 login = new A31();
       login.setVisible(true);
    }//GEN-LAST:event_ContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3Cadstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3Cadstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3Cadstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3Cadstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A3Cadstro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CEP;
    private javax.swing.JTextField CPF;
    private javax.swing.JTextField Compl;
    private javax.swing.JTextField ConfirmaS;
    private javax.swing.JButton Continuar;
    private javax.swing.JTextField DataNascimento;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField NomeC;
    private javax.swing.JTextField Nresidencia;
    private javax.swing.JTextField Senha;
    private javax.swing.JTextField Tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
