/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3st;

/**
 *
 * @author tiago
 */
public class A3Dados extends javax.swing.JFrame {

    /**
     * Creates new form A3Dados
     */
    public A3Dados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Coração = new javax.swing.JButton();
        Familia = new javax.swing.JButton();
        Remedios = new javax.swing.JButton();
        Telefone = new javax.swing.JButton();
        Alergia = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Seta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 780));
        getContentPane().setLayout(null);

        Coração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoraçãoActionPerformed(evt);
            }
        });
        getContentPane().add(Coração);
        Coração.setBounds(110, 280, 80, 80);

        Familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamiliaActionPerformed(evt);
            }
        });
        getContentPane().add(Familia);
        Familia.setBounds(330, 280, 80, 80);

        Remedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemediosActionPerformed(evt);
            }
        });
        getContentPane().add(Remedios);
        Remedios.setBounds(560, 280, 80, 80);

        Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(Telefone);
        Telefone.setBounds(450, 420, 80, 80);

        Alergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlergiaActionPerformed(evt);
            }
        });
        getContentPane().add(Alergia);
        Alergia.setBounds(220, 420, 80, 80);

        jTextField1.setBackground(new java.awt.Color(19, 107, 105));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 110, 370, 22);

        jTextField2.setBackground(new java.awt.Color(19, 107, 105));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 170, 220, 22);

        Seta.setBackground(new java.awt.Color(170, 191, 184));
        Seta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Seta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetaActionPerformed(evt);
            }
        });
        getContentPane().add(Seta);
        Seta.setBounds(0, 10, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danil\\OneDrive\\Documentos\\Faculdade\\imgA3\\Dados.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 6, 1060, 547);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamiliaActionPerformed
       A3CDF familia = new A3CDF();
       familia.setVisible(true);
    }//GEN-LAST:event_FamiliaActionPerformed

    private void SetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetaActionPerformed
        A31 lgin = new A31();
        lgin.setVisible(true);
    }//GEN-LAST:event_SetaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CoraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoraçãoActionPerformed
        A3Dcronicas cronicas =  new A3Dcronicas();
        cronicas.setVisible(true);
    }//GEN-LAST:event_CoraçãoActionPerformed

    private void RemediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemediosActionPerformed
        A3MUC medicamentos = new A3MUC();
        medicamentos.setVisible(true);
    }//GEN-LAST:event_RemediosActionPerformed

    private void AlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlergiaActionPerformed
        A3ALM alergia = new A3ALM();
        alergia.setVisible(true);
                
    }//GEN-LAST:event_AlergiaActionPerformed

    private void TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneActionPerformed
        A3CE emergencia = new A3CE();
        emergencia.setVisible(true);
    }//GEN-LAST:event_TelefoneActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A3Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alergia;
    private javax.swing.JButton Coração;
    private javax.swing.JButton Familia;
    private javax.swing.JButton Remedios;
    private javax.swing.JButton Seta;
    private javax.swing.JButton Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
