/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3st;

/**
 *
 * @author tiago
 */
public class A3Dados extends javax.swing.JFrame {

    /**
     * Creates new form A3Dados
     */
    public A3Dados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Coração = new javax.swing.JButton();
        Familia = new javax.swing.JButton();
        Cirurgias = new javax.swing.JButton();
        Remedios = new javax.swing.JButton();
        Telefone = new javax.swing.JButton();
        Alergia = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Vinicio = new javax.swing.JButton();
        Seta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 780));
        getContentPane().setLayout(null);

        Coração.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\doenca-cardiaca.png")); // NOI18N
        Coração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoraçãoActionPerformed(evt);
            }
        });
        getContentPane().add(Coração);
        Coração.setBounds(250, 420, 80, 80);

        Familia.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\familia.png")); // NOI18N
        Familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamiliaActionPerformed(evt);
            }
        });
        getContentPane().add(Familia);
        Familia.setBounds(500, 420, 80, 80);

        Cirurgias.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\luva.png")); // NOI18N
        Cirurgias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirurgiasActionPerformed(evt);
            }
        });
        getContentPane().add(Cirurgias);
        Cirurgias.setBounds(500, 580, 80, 80);

        Remedios.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\medicacao.png")); // NOI18N
        Remedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemediosActionPerformed(evt);
            }
        });
        getContentPane().add(Remedios);
        Remedios.setBounds(750, 420, 80, 80);

        Telefone.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\telefone.png")); // NOI18N
        Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(Telefone);
        Telefone.setBounds(750, 580, 80, 80);

        Alergia.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\alergia-a-drogas.png")); // NOI18N
        Alergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlergiaActionPerformed(evt);
            }
        });
        getContentPane().add(Alergia);
        Alergia.setBounds(250, 580, 80, 80);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 170, 420, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 270, 220, 22);

        Vinicio.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\casa.png")); // NOI18N
        Vinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VinicioActionPerformed(evt);
            }
        });
        getContentPane().add(Vinicio);
        Vinicio.setBounds(10, 680, 70, 70);

        Seta.setBackground(new java.awt.Color(170, 191, 184));
        Seta.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\setas-pretas-para-a-esquerda.png")); // NOI18N
        Seta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Seta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetaActionPerformed(evt);
            }
        });
        getContentPane().add(Seta);
        Seta.setBounds(0, 10, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\7Dados.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 6, 1060, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamiliaActionPerformed
       A3CDF familia = new A3CDF();
       familia.setVisible(true);
    }//GEN-LAST:event_FamiliaActionPerformed

    private void VinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VinicioActionPerformed
         a3f Dados = new a3f();
         Dados.setVisible(true);
    }//GEN-LAST:event_VinicioActionPerformed

    private void SetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetaActionPerformed
        A31 lgin = new A31();
        lgin.setVisible(true);
    }//GEN-LAST:event_SetaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CoraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoraçãoActionPerformed
        A3Dcronicas cronicas =  new A3Dcronicas();
        cronicas.setVisible(true);
    }//GEN-LAST:event_CoraçãoActionPerformed

    private void RemediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemediosActionPerformed
        A3MUC medicamentos = new A3MUC();
        medicamentos.setVisible(true);
    }//GEN-LAST:event_RemediosActionPerformed

    private void AlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlergiaActionPerformed
        A3ALM alergia = new A3ALM();
        alergia.setVisible(true);
                
    }//GEN-LAST:event_AlergiaActionPerformed

    private void CirurgiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirurgiasActionPerformed
       A3HC cirurgia = new A3HC();
       cirurgia.setVisible(true);
    }//GEN-LAST:event_CirurgiasActionPerformed

    private void TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneActionPerformed
        A3CE emergencia = new A3CE();
        emergencia.setVisible(true);
    }//GEN-LAST:event_TelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A3Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alergia;
    private javax.swing.JButton Cirurgias;
    private javax.swing.JButton Coração;
    private javax.swing.JButton Familia;
    private javax.swing.JButton Remedios;
    private javax.swing.JButton Seta;
    private javax.swing.JButton Telefone;
    private javax.swing.JButton Vinicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
