/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3st;

/**
 *
 * @author tiago
 */
public class A3instituição extends javax.swing.JFrame {

    /**
     * Creates new form A3instituição
     */
    public A3instituição() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Senha = new javax.swing.JTextField();
        Cacesso = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        Cadastro = new javax.swing.JButton();
        RecuperarSenha = new javax.swing.JButton();
        TrocaUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(785, 590));
        getContentPane().setLayout(null);

        Senha.setText("Senha");
        getContentPane().add(Senha);
        Senha.setBounds(50, 260, 250, 22);

        Cacesso.setText("Codigo de acesso");
        Cacesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CacessoActionPerformed(evt);
            }
        });
        getContentPane().add(Cacesso);
        Cacesso.setBounds(50, 190, 250, 22);

        Entrar.setText("Entrar");
        Entrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Entrar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar);
        Entrar.setBounds(130, 360, 80, 30);

        Cadastro.setText("Cadastro");
        Cadastro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Cadastro.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastro);
        Cadastro.setBounds(530, 280, 90, 30);

        RecuperarSenha.setText("Recuperar a senha");
        RecuperarSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RecuperarSenha.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        RecuperarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecuperarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(RecuperarSenha);
        RecuperarSenha.setBounds(360, 520, 140, 22);

        TrocaUser.setText("Trocar user");
        TrocaUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TrocaUser.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        getContentPane().add(TrocaUser);
        TrocaUser.setBounds(665, 520, 100, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\Logininst.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 774, 552);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        A3Cpaciente paciente = new A3Cpaciente();
        paciente.setVisible(true);
    }//GEN-LAST:event_EntrarActionPerformed

    private void CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroActionPerformed
        Cadastro2 cdstro = new Cadastro2();
        cdstro.setVisible(true);
    }//GEN-LAST:event_CadastroActionPerformed

    private void RecuperarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecuperarSenhaActionPerformed
        AERsenha2 Rsenha = new AERsenha2();
        Rsenha.setVisible(true);
    }//GEN-LAST:event_RecuperarSenhaActionPerformed

    private void CacessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CacessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CacessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3instituição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3instituição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3instituição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3instituição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A3instituição().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cacesso;
    private javax.swing.JButton Cadastro;
    private javax.swing.JButton Entrar;
    private javax.swing.JButton RecuperarSenha;
    private javax.swing.JTextField Senha;
    private javax.swing.JButton TrocaUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
