/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3st;

/**
 *
 * @author tiago
 */
public class Cadastro2 extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro2
     */
    public Cadastro2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeInst = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        CEP = new javax.swing.JTextField();
        CNPJ = new javax.swing.JTextField();
        Num = new javax.swing.JTextField();
        Complemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Continuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(790, 580));
        getContentPane().setLayout(null);

        NomeInst.setText("Nome da instituição");
        getContentPane().add(NomeInst);
        NomeInst.setBounds(100, 180, 250, 22);

        Email.setText("E-mail");
        getContentPane().add(Email);
        Email.setBounds(100, 220, 250, 22);

        CEP.setText("CEP");
        getContentPane().add(CEP);
        CEP.setBounds(100, 300, 250, 22);

        CNPJ.setText("CNPJ");
        getContentPane().add(CNPJ);
        CNPJ.setBounds(460, 180, 260, 22);

        Num.setText("Numero");
        getContentPane().add(Num);
        Num.setBounds(460, 300, 260, 22);

        Complemento.setText("Complemento");
        getContentPane().add(Complemento);
        Complemento.setBounds(460, 370, 260, 20);

        jLabel2.setText("Endereço");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 280, 90, 16);

        Continuar.setText("Continuar");
        Continuar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Continuar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(Continuar);
        Continuar.setBounds(320, 450, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Tiago\\faculdade\\imgA3\\Cadastro2.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 774, 549);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
        A3Cadastro3 cdastro2 = new A3Cadastro3();
        cdastro2.setVisible(true);
    }//GEN-LAST:event_ContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CEP;
    private javax.swing.JTextField CNPJ;
    private javax.swing.JTextField Complemento;
    private javax.swing.JButton Continuar;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField NomeInst;
    private javax.swing.JTextField Num;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
